# text representation

In [50]:
import numpy as np
import pandas as pd

In [51]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [52]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

- bag of words or unigrams

In [54]:
cv = CountVectorizer()

In [55]:
bow = cv.fit_transform(df['text'])

In [56]:
# vocab
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [57]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [58]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

- bigrams


In [59]:
cv = CountVectorizer(ngram_range=(2,2))


In [60]:
bow = cv.fit_transform(df['text'])

In [61]:
# vocab
cv.vocabulary_

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comment': 5,
 'campusx write': 1}

- ungrams + bigrams

In [62]:
cv = CountVectorizer(ngram_range=(1,2))


In [63]:
bow = cv.fit_transform(df['text'])

In [64]:
# vocab
cv.vocabulary_

{'people': 4,
 'watch': 7,
 'campusx': 0,
 'people watch': 5,
 'watch campusx': 8,
 'campusx watch': 1,
 'write': 9,
 'comment': 3,
 'people write': 6,
 'write comment': 10,
 'campusx write': 2}

- trigrams

In [65]:
cv = CountVectorizer(ngram_range=(3,3)) #cant be more than 3 words as a sentence contains max of 3 words

bow = cv.fit_transform(df['text'])
# vocab
cv.vocabulary_

{'people watch campusx': 2,
 'campusx watch campusx': 0,
 'people write comment': 3,
 'campusx write comment': 1}

- combo of uni, bi and tri

In [66]:
cv = CountVectorizer(ngram_range=(1,3)) #cant be more than 3 words as a sentence contains max of 3 words

bow = cv.fit_transform(df['text'])
# vocab
cv.vocabulary_

{'people': 6,
 'watch': 11,
 'campusx': 0,
 'people watch': 7,
 'watch campusx': 12,
 'people watch campusx': 8,
 'campusx watch': 1,
 'campusx watch campusx': 2,
 'write': 13,
 'comment': 5,
 'people write': 9,
 'write comment': 14,
 'people write comment': 10,
 'campusx write': 3,
 'campusx write comment': 4}

- TF IDF

In [67]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [70]:
tdidf = TfidfVectorizer()
print("TFIDF = ",tdidf.fit_transform(df['text']).toarray())

# --------------------------------

print("\n\n IDF = ",tdidf.idf_)

# IDF = log[n/df(t)]+1 (if smooth_idf=false)
print("\n\n Get features = ",tdidf.get_feature_names_out)

TFIDF =  [[0.49681612 0.         0.61366674 0.61366674 0.        ]
 [0.8508161  0.         0.         0.52546357 0.        ]
 [0.         0.57735027 0.57735027 0.         0.57735027]
 [0.49681612 0.61366674 0.         0.         0.61366674]]


 IDF =  [1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


 Get features =  <bound method CountVectorizer.get_feature_names_out of TfidfVectorizer()>
